services:
    parse.sdk.push:
        class: Gkocakaya\ParseSdkBundle\Parse\Push
        arguments:
            - %gkocakaya_parse_sdk.app_id%
            - %gkocakaya_parse_sdk.rest_key%
            - %gkocakaya_parse_sdk.master_key%
